name: Build CI release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        run: |
          curl -O https://cdn.azul.com/zulu/bin/zulu21.32.17-ca-fx-jdk21.0.2-linux_amd64.deb
          sudo apt-get -y install ./zulu21.32.17-ca-fx-jdk21.0.2-linux_amd64.deb
      - name: Environment setup
        env:
          DISPLAY: :99
        run: |
          sudo apt install -y wine xvfb
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32
          wget http://files.jrsoftware.org/is/6/innosetup-6.2.2.exe -O is.exe
          Xvfb $DISPLAY &
          wine wineboot --init
          wine is.exe /VERYSILENT /SUPPRESSMSGBOXES
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          export JAVA_HOME=/usr/lib/jvm/zulu-fx-21-amd64/
          cd Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          ./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Quelea/dist/standalone/*
          tag: CI-RELEASE
          overwrite: true
          prerelease: true
          make_latest: false
          file_glob: true
          body: "**This is a CI Build, built from the latest copy of the source code automatically. It's not an official release and we don't recommend using this in production.**<br/>Quelea is also distributed as a Linux snap package. To install it, make sure snap is installed then run:<pre>sudo snap install --edge quelea</pre>"